LOCAL_DIR := $(GET_LOCAL_DIR)

MODULE := $(LOCAL_DIR)

BOOTLOADER_FB_ADDRESS ?= 0xf1000000

MODULE_SRCS += \
	$(LOCAL_DIR)/exynos_font.c \

GLOBAL_DEFINES += \
	BOOTLOADER_FB_ADDRESS=$(BOOTLOADER_FB_ADDRESS) \
	LCD_WIDTH=$(LCD_WIDTH) \
	LCD_HEIGHT=$(LCD_HEIGHT) \

include make/module.mk
